export const TEST_BUILDER_ROUTE = '/test_builder'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const TEST_ROUTE = '/test'
export const MY_TESTS_ROUTE = '/my-tests'
export const COMPLETED_TESTS = '/completed-tests'
export const MAIN_ROUTE = '/main'
export const PRIVATE_OFFICE_ROUTE = '/private_office'